### ISSUE TITLE
Keras version differences

### ISSUE THREAD

**Issue by Wuhn** [idiap/mhan#1]
Hi,

first of all thanks a lot for publishing the code!

I have a question regarding the documented keras version. It is said to be .v 1.2.2, however in _models.py_  you are importing `from keras.layers.merge` which then throws the error that there is no module named merge. Are you by any chance using a newer version?

I think if you want to use it in keras 1.2.2 you have to do:
`from keras.layers import Merge `
and then do:
`Merge([forward_words, backward_words],mode='concat', concat_axis=1)` or  `Merge([weights, forward_words], mode='mul')` instead of `Multiply()([weights, forward_words])`

Also `from keras.utils import plot_model` is still  `from keras.utils.visualize_util import plot` in keras 1.2.2

There seem to be some dependencies missing:

- sklearn
- pydot-ng

Best wishes,
Ji-Ung

**Comment by nik0spapp** [comment]
Thanks for reporting this issue and missing dependencies! 

Indeed, you are right the original version was 1.2.2 but for the open source version we changed it to make it compatible with latest versions. I will modify the code soon to support both. 
 
Best regards,
Nikos

**Comment by Wuhn** [comment]
Thank you for your reply! A small update regarding the versioning, since I found this in the text:

> The examples below were run on GPU with Keras==2.0.8, Theano==0.9.0, numpy==1.13.3, CUDA v8.0.44 and cuDNN 5110.

Which is great, because I am running most of my stuff on keras>=2 too. For keras 2.0.8 I had to make two changes:

1. I had to modify **model.py** like this (there was a `self.` missing for the random seed):
```
181    if self.args['seed'] is not None:
182	    np.random.seed(self.args['seed'])
```

2. I also had to convert the labels for the keras.utils.to_categorical() function in **util.py** . When using the downloaded data using your fetch_data.py script, the label_ids are [225, 986, 1011, 444]. The function load_vectors() tries to use them in plain format for creating the proper format for y, which throws an IndexError:

```
Traceback (most recent call last):
  File "run.py", line 103, in <module>
    mhan.fit(X_ids, Y_ids, XV_ids, YV_ids, labels, wvecs, vocabs)
  File "../mhan/models.py", line 295, in fit
    self.args['swpad'], self.args['spad'])
  File "../mhan/util.py", line 65, in load_vectors
    y_cats =  np.sum(to_categorical(y_idxs[idx], num_classes=len(labels)),axis=0)
  File "../lib/python2.7/site-packages/keras/utils/np_utils.py", line 25, in to_categorical
    categorical[np.arange(n), y] = 1
IndexError: index 986 is out of bounds for axis 1 with size 4
```

So I modified them accordingly (map all classes to [0 - number_of_classes] using a dictionary for the labels) and I think it works now.

**Comment by nik0spapp** [comment]
This is very helpful, thanks for pointing them out. I have fixed the first issue and looking into the second one. It must be also related to the changes done for supporting for the latest Keras version.

**Comment by nik0spapp** [comment]
Hi Wuhn, 

Could you please give few details about your second point above? Is the formatting of y_idxs from fetch_data.py incompatible with to_categorical function or the arguments of to_categorical were not compatible with your keras version?  I only spotted a potential versioning issue with the argument num_classes and nb_classes.  

Thanks,
Nikos

**Comment by Wuhn** [comment]
Hi Nikos,

I think the problem is that in the data I downloaded with fetch_data.py there are only 4 classes with `label_ids = [225, 986, 1011, 444]` and those are used as the label indices in load_vectors(). 

So when passing 986 to `categorical[np.arange(n), y] = 1`  in `keras.utils.to_categorical` with` n=4` classes, an IndexError is thrown because there is no 986th element. What I did to fix it was to create new label indices for the data, e.g.:
`label_index_dict = dict((label,i) for i, label in enumerate(sorted([int(element) for element in labels])))` 
as a dictionary with the new indexing. Afterwards I mapped the labels to the according indices (in this example 255->0, 444->1, 986->2, 1011->3 ) and used those for training/testing. I guess alternatively you could also modify fetch_data.py , however, I did not look into that. 

The code works fine, if `max(label_ids) == number_of_classes` , so this could only be a occurring in my case.

Best,
Ji-Ung

**Comment by nik0spapp** [comment]
I would like to fix this issue, thanks for the additional information. Which command did you use to download the data? It is a bit odd to have only four classes. Did the script run all the way to the end or it was terminated abruptly?

**Comment by Wuhn** [comment]
I used the one in the Readme:
`python fetch_data.py --lang german --urlpath data_urls/dw_general --outpath data/dw_general --ltype rou` 
I am not sure why but it seems to not load all of the data. However, it finishes without any errors so I thought it is ok for testing purposes:
```
[*] Loading german word vectors...
	word_vectors/german.pkl                                    OK
[*] Fetching dev data...
	german (5/13264)
Skipped: 0
[*] Fetching test data...
	german (5/13265)
Skipped: 0
[*] Fetching training data...
	german (5/106181)
Skipped: 0
[*] Storing dev data...
[*] Storing test data...
[*] Storing training data...
[-] Finished.
```
By the way, get_label_counts() is the only function written with 4 spaces instead of tabs, you may want to change that to be consistent throughout your code =).

**Comment by nik0spapp** [comment]
Great! OK, I fixed the issue. The loop was only downloading only five URLs, but this was only for testing purposes. I have now changed the loop to go through all the URLs in the dataset. That explains why you had few classes in total. 

Now it should be fine, I am closing the issue. 

Thanks again for your nice feedback!

**Comment by Wuhn** [comment]
You are welcome! Thanks again for sharing the code and the quick responses!
