### ISSUE TITLE
No file "index.html" in visualisation folder

### ISSUE THREAD

**Issue by lstappen** [idiap/mhan#3]
> **Loading the files obtained with --store_test argument**
> [...]
> 4. Open index.html in a browser (recommended one is Firefox).

Hi,

index.html is not uploaded to the visualisation folder  (https://github.com/idiap/mhan/tree/master/visualization). Opening explore.html instead does only show the loading sign. Help is much appreciated!

Cheers,
Lukas

**Comment by lstappen** [comment]
Got it to work by changing the filename (explore to index) and the filename of the exported file "parametername" + "_" + language + ".json"

explore.js gave me the right hint:
`_"+lang+".json`

It still might be sensible to update the documentation. Either way great work guys!

**Comment by nik0spapp** [comment]
Thanks for pointing out this mistake in the documentation. We will update it based on your suggestion.  

Cheers,
Nikos
