### ISSUE TITLE
fetch_data retrieves text from "related stories" - captions

### ISSUE THREAD

**Issue by martingerlach** [idiap/mhan#4]
Thank you for sharing this resource -- I found it very useful for easily obtaining annotated news-articles from different languages. However, I think there might be an issue with the text that is being retrieved for the individual articles. 

Some of the news-articles contain "related-stories" section below the end of the text. The problem is that when you retrieve the text via ```body = soup.findAll```, the captions of all these photographs are added to the text ("sentences"). Sometimes, these are up to 30 (or more) photographs, so the text from the captions will make up the bulk of the text. As a result, this will introduce a lot of "noise" into the data and artificially increase its size.

For example, http://dw.com/p/1Gp0V is an article about a zoo in denmark. However, the bulk of the text retrieved in the code will come from the captions of 9 photos related to "Best wildlife photos of 2015".

This is a minimal code should reproduce this behaviour (in your code you dont save the text but only consider the word-vectors from some vocabulary, but this should still be effected by this artifact). 
```
import sys, json, time, os
import argparse, urllib2
from bs4 import BeautifulSoup
from nltk.tokenize import sent_tokenize, word_tokenize

def clean(text):
    text = text.replace('\n', ' ')
    text = text.replace('\r', ' ')
    return text.replace('\t', ' ')

url = 'http://dw.com/p/1Gp0V'
title, teaser, body = "", "", ""
try:
    response = urllib2.urlopen(url)
    soup = BeautifulSoup(response.read(), 'html.parser')
    time.sleep(0.5)
except:
    print "URL not found: %s" % url

    
try:
    title = soup.h1.text.lower()
except:
    pass
try:
    teaser =  soup.findAll("p", { "class" : "intro" })[0].text.lower()
except:
    pass
try:
    body = soup.findAll("div", { "class" : "longText" })[0].text.lower()
except:
    pass

sentences = [clean(title)]
sentences += sent_tokenize(clean(teaser).strip())
sentences += sent_tokenize(clean(body.strip()))
print sentences
```

The workaround I used was that these captions are separated from the news-texts by '               ' (15 whitespaces), such that one could do:
```
text = []
for sentence in sentences:
    text += [sentence]
text = ' '.join(text)
text = text.split('               ')[0]
```

Would be curious to know what you think, since I think this is a really cool dataset.
Best,
Martin

**Comment by nik0spapp** [comment]
Hello Martin, 

Thanks a lot for reporting this issue and suggesting a workaround! I'd be glad to incorporate this change into the crawling script. 

The workaround you recommend will solve the issue for now. Hopefully, they won't change their webpage structure any time soon.  If time permits, I would like to find a more general solution that will filter out the HTML region by its class (e.g. related-stories).

The good thing is that this script is an independent implementation of the original. The data were initially crawled by another partner in the project but their script was not publicly available, so this issue has most likely not affected the text collection used in the paper. 

Let me know if you are interested in the original pre-processed version of the data and I will send them to you via email. 

Best,
Nikos

**Comment by nik0spapp** [comment]
Following up my reply above, I found another solution which filters out the region based on its class attribute. 

```
    region = soup.findAll("div", { "class" : "longText" })[0]
    related_stories = region.find('div', {'class':'gallery'})
    if related_stories is not None:    
	related_stories.decompose() # remove related stories
    body = region.text.lower()
```

Let me know if that works for you and I will close the issue.

**Comment by martingerlach** [comment]
Nikos,
thanks for the quick reply.
Yes, the solution you mention in your previous post seems to filter out the picture galleries and their captions.
Great.
Thanks again.
