### ISSUE TITLE
MultiCCA UnicodeDecodeError

### ISSUE THREAD

**Issue by luna1991** [idiap/mhan#5]
Hi,

I am trying to use the multicca embeddings availabel in the repo, but when I load the pickled file, I always get the following error:

`UnicodeDecodeError: 'ascii' codec can't decode byte 0x88 in position 1: ordinal not in range(128)`

Any suggestions how to solve this?

**Comment by nik0spapp** [comment]
Hello, 

Which version of python are you using? The following snippet should work with Python 2.7:

```python
import pickle
import gzip
arabic_embedding = pickle.load(gzip.open('arabic.pkl.gz'))
```
Hope it helps. 

Best regards,
Nikos

**Comment by luna1991** [comment]
Hello Nikos,

I am using python version 3.6
Is there anyway to get the files compatible with the newer python versions?

Best regards,
Luna

**Comment by nik0spapp** [comment]
Here is a workaround for making it work with Python 3.6:

```python
arabic_embedding = pickle.load(gzip.open('arabic.pkl.gz'), encoding='latin1')
```
You can find more details about the issue here: https://stackoverflow.com/questions/28218466/unpickling-a-python-2-object-with-python-3

Best,
Nikos

**Comment by luna1991** [comment]
This works. Thank you!
