### ISSUE TITLE
Bug in fetch_data.py

### ISSUE THREAD

**Issue by YipingNUS** [idiap/mhan#6]
Hi @nik0spapp 

In fetch_data.py it only reindexes the training set. Shouldn't it reindex the dev and test set as well to make it consistent?

``` Python
X, Y = fetch_data(urls_train['urls'], args.lang, vocab, args.ltype)
	yh = get_label_counts(Y+Y_dev+Y_test, args.lang)
	Y = re_index(Y, yh.keys())
```
I was trying to run the GILE pretrained English model on the DW general dataset.

```
python run.py --test --path pretrained/enc-gen/gile-han-bigru/ --data_path data/dw_general/ --languages english --target english --la --t 0.4
```
And it gives the following error:

```
Traceback (most recent call last):
  File "run.py", line 132, in <module>
    reals, epreds = han.eval(lang_idx, XT_ids[lang_idx], YT_ids[lang_idx], wvecs[lang_idx], labels[lang_idx], L=len(args['languages']))
  File "/home/yiping/semi-supervised/gile/han.py", line 485, in eval
    x_vecs, y_vecs = load_vectors(wvec, labels, cur_x, cur_y, self.args['swpad'], self.args['spad'])
  File "/home/yiping/semi-supervised/gile/util.py", line 74, in load_vectors
    y_cats = np.sum(to_categorical(y_idxs[idx], num_classes=len(labels)), axis=0)
  File "/home/yiping/anaconda3/envs/tf_gpu/lib/python3.6/site-packages/tensorflow/python/keras/utils/np_utils.py", line 49, in to_categorical
    categorical[np.arange(n), y] = 1
IndexError: index 140 is out of bounds for axis 1 with size 13
```
Which I interpret as `140` is the word id, `13` is the total number of labels. Since the test set and dev set labels are word ids, this error occurs. When I use the train set (reindexed) to test, it works.

Also another issue trying to run the pretrained English model. The model's arg file specifies ladim=None, which means the model will use a ladim derived from other parameters. When I was trying to run the model on a sample dataset, the ladim got different from the pretrained model (which is 233). So I recommend you change the paremeter ladim in `args.json` to the value in the pretrained model to avoid the trouble.

**Comment by nik0spapp** [comment]
Thanks for pointing out this issue and for the suggestion! 

Recently, I added the re-index function but forgot to apply it to all the target sets. Now, it is fixed. 

I also updated the args.json with your suggestion for the English model (gile-han-bigru). Feel free to open an issue at the [gile](https://github.com/idiap/gile) repository if you have any other questions.
